# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbc2bb86fdc07a27f48904c74ec4535ce76c7001cc6ad0a7e70d184da590da0a5da775e941fe67c4de1f9c40506ada2655c69e38e202890c1645baf73e403eda

test:
  secret_key_base: 3461c2c362520cf9486d50fe42a6986fe7ce1c729839c8448467d41622f9e2b79b9b8fdf2353bb497432033b9da48aeae451e33a7f283f341594a4ab38bfae7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
